app = "frendle-signaling"
primary_region = "sea"

[build]
builder = ""

[env]
PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  [services.concurrency]
    type = "connections"
    hard_limit = 55
    soft_limit = 50

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
