/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UikitImport } from './routes/uikit'
import { Route as TermsImport } from './routes/terms'
import { Route as SessionImport } from './routes/session'
import { Route as ResourcesImport } from './routes/resources'
import { Route as ProfileImport } from './routes/profile'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as OnboardingImport } from './routes/onboarding'
import { Route as MatchImport } from './routes/match'
import { Route as LoginImport } from './routes/login'
import { Route as ExpectationsImport } from './routes/expectations'
import { Route as DonationImport } from './routes/donation'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AuthCallbackImport } from './routes/auth/callback'

// Create/Update Routes

const UikitRoute = UikitImport.update({
  id: '/uikit',
  path: '/uikit',
  getParentRoute: () => rootRoute,
} as any)

const TermsRoute = TermsImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRoute,
} as any)

const SessionRoute = SessionImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRoute,
} as any)

const ResourcesRoute = ResourcesImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const OnboardingRoute = OnboardingImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRoute,
} as any)

const MatchRoute = MatchImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ExpectationsRoute = ExpectationsImport.update({
  id: '/expectations',
  path: '/expectations',
  getParentRoute: () => rootRoute,
} as any)

const DonationRoute = DonationImport.update({
  id: '/donation',
  path: '/donation',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthCallbackRoute = AuthCallbackImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/donation': {
      id: '/donation'
      path: '/donation'
      fullPath: '/donation'
      preLoaderRoute: typeof DonationImport
      parentRoute: typeof rootRoute
    }
    '/expectations': {
      id: '/expectations'
      path: '/expectations'
      fullPath: '/expectations'
      preLoaderRoute: typeof ExpectationsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchImport
      parentRoute: typeof rootRoute
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesImport
      parentRoute: typeof rootRoute
    }
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionImport
      parentRoute: typeof rootRoute
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsImport
      parentRoute: typeof rootRoute
    }
    '/uikit': {
      id: '/uikit'
      path: '/uikit'
      fullPath: '/uikit'
      preLoaderRoute: typeof UikitImport
      parentRoute: typeof rootRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donation': typeof DonationRoute
  '/expectations': typeof ExpectationsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/terms': typeof TermsRoute
  '/uikit': typeof UikitRoute
  '/auth/callback': typeof AuthCallbackRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donation': typeof DonationRoute
  '/expectations': typeof ExpectationsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/terms': typeof TermsRoute
  '/uikit': typeof UikitRoute
  '/auth/callback': typeof AuthCallbackRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donation': typeof DonationRoute
  '/expectations': typeof ExpectationsRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/resources': typeof ResourcesRoute
  '/session': typeof SessionRoute
  '/terms': typeof TermsRoute
  '/uikit': typeof UikitRoute
  '/auth/callback': typeof AuthCallbackRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donation'
    | '/expectations'
    | '/login'
    | '/match'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/session'
    | '/terms'
    | '/uikit'
    | '/auth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donation'
    | '/expectations'
    | '/login'
    | '/match'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/session'
    | '/terms'
    | '/uikit'
    | '/auth/callback'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donation'
    | '/expectations'
    | '/login'
    | '/match'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/resources'
    | '/session'
    | '/terms'
    | '/uikit'
    | '/auth/callback'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonationRoute: typeof DonationRoute
  ExpectationsRoute: typeof ExpectationsRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResourcesRoute: typeof ResourcesRoute
  SessionRoute: typeof SessionRoute
  TermsRoute: typeof TermsRoute
  UikitRoute: typeof UikitRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonationRoute: DonationRoute,
  ExpectationsRoute: ExpectationsRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResourcesRoute: ResourcesRoute,
  SessionRoute: SessionRoute,
  TermsRoute: TermsRoute,
  UikitRoute: UikitRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/donation",
        "/expectations",
        "/login",
        "/match",
        "/onboarding",
        "/privacy",
        "/profile",
        "/resources",
        "/session",
        "/terms",
        "/uikit",
        "/auth/callback"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/donation": {
      "filePath": "donation.tsx"
    },
    "/expectations": {
      "filePath": "expectations.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/match": {
      "filePath": "match.tsx"
    },
    "/onboarding": {
      "filePath": "onboarding.tsx"
    },
    "/privacy": {
      "filePath": "privacy.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/resources": {
      "filePath": "resources.tsx"
    },
    "/session": {
      "filePath": "session.tsx"
    },
    "/terms": {
      "filePath": "terms.tsx"
    },
    "/uikit": {
      "filePath": "uikit.tsx"
    },
    "/auth/callback": {
      "filePath": "auth/callback.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
